// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBju3VEC0mQS1BeY6OVG10-HAo9Zoa2dgs',
    appId: '1:83754170120:web:70c24e672ba1f6d5205ebd',
    messagingSenderId: '83754170120',
    projectId: 'md-final-1e3c0',
    authDomain: 'md-final-1e3c0.firebaseapp.com',
    storageBucket: 'md-final-1e3c0.firebasestorage.app',
    measurementId: 'G-NSSDRXN6BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBHjjsUHLecvlvFfyzkcpmOArGLE5bdQ',
    appId: '1:83754170120:android:ffe65af008e208f5205ebd',
    messagingSenderId: '83754170120',
    projectId: 'md-final-1e3c0',
    storageBucket: 'md-final-1e3c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeGre_96rTYUNHDCl54E2-Kw3zFES4aw',
    appId: '1:83754170120:ios:86f8028f7e2cc433205ebd',
    messagingSenderId: '83754170120',
    projectId: 'md-final-1e3c0',
    storageBucket: 'md-final-1e3c0.firebasestorage.app',
    iosBundleId: 'com.example.mdFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZeGre_96rTYUNHDCl54E2-Kw3zFES4aw',
    appId: '1:83754170120:ios:86f8028f7e2cc433205ebd',
    messagingSenderId: '83754170120',
    projectId: 'md-final-1e3c0',
    storageBucket: 'md-final-1e3c0.firebasestorage.app',
    iosBundleId: 'com.example.mdFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBju3VEC0mQS1BeY6OVG10-HAo9Zoa2dgs',
    appId: '1:83754170120:web:7b78b884c4464d78205ebd',
    messagingSenderId: '83754170120',
    projectId: 'md-final-1e3c0',
    authDomain: 'md-final-1e3c0.firebaseapp.com',
    storageBucket: 'md-final-1e3c0.firebasestorage.app',
    measurementId: 'G-EC16LYCEYX',
  );
}
